dashboards/sidekiq/main.yml

If we use the wildcard to show duration metrics from all namespaces it contains
more than just Sidekiq worker metrics, but also controllers from the web
namespace for example. To remedy this, limit the namespace to the background
namespace.
This is only a problem if the user has overwritten the namespace in which case
they need to tweak this after the magic dashboard has been added.

Limit Sidekiq metrics to background namespace

---

dashboards/sidekiq/main.yml

They're all gauges, not counters or measurements.

Fix Sidekiq metric fields

---

dashboards/puma/main.yml

Not sure if it's a good idea to add descriptions to all graphs, threads/workers seem self explanatory to me, but maybe I'm biased?

Add descriptions for puma dashboard graphs

---

dashboards/erlang/main.yml

We currently don't set the proper formatting for this metric, by setting
the `format: size` we do.
Fixes: #14

Use Format: Size for erlang memory metric

---

dashboards/heroku/postgres.yml

The range Heroku emits is 0-1, but we use the percentage formatter, this shows a `1` cache (`100%`) as `1%`. 
To keep the value we show consistent with their documentation, change the formatter from `percentage` to `number`

Update formatter for Heroku Postgres cache rate

---

dashboards/erlang/main.yml

You can see how the metrics are collected here:
https://github.com/appsignal/appsignal-elixir/blob/350d8db1b3943456aa6f987afac8831cdad4f094/lib/appsignal/probes/erlang_probe.ex#L39

Show memory in units that are collected in probe

---

dashboards/heroku/redis.json

* Add Heroku Redis dashboard
* Refactor Heroku postresql dashboard to only show postgres host metrics
Both dashboards have host metrics (memory/iops) and Heroku emits those with the same keys.
Instead of a wildcard tag we now use `postgreslq-*` and `redis-*` to filter out the correct host tags.

Add Heroku Redis dashboard

---

dashboards/active_job/main.json

Relies on https://github.com/appsignal/appsignal-ruby/pull/633
Add Active Job magic dashboard definition to show processed job count
metrics. It shows the total number of processed jobs and how many jobs
failed while being processed.
Metric naming format same as used by the Sidekiq integration.

Add Active Job magic dashboard definition

---

dashboards/active_job/main.json

Add an extra graph that shows the priorities per queue. The dashboard
will report a breakdown per queue, and per queue and priorities.
This is the update required by
https://github.com/appsignal/appsignal-ruby/pull/643

Update Active Job dashboard for priorities

---

dashboards/active_job/main.json

The Sidekiq dashboard also has these graphs, I copied them from there.
It shows the throughput for all actions in the "background" namespace
and the duration for those actions in the "background" namespace.
These two graphs make the dashboard more complete and provides more
information based on the `transaction_duration` metric.
Also be more clear that the priority graph can be empty if the adapter
doesn't support it.

Add throughput and duration graphs to ActiveJob

---

dashboards/action_mailer/main.json

Add ActionMailer dashboard with two graphs:
* One for throughput per mailer/method combination
* One that shows a relative percentage graph (e.g. "stacked graph") to quickly identify what mailer took up most resources.
Related: https://github.com/appsignal/appsignal-ruby/pull/669

Add ActionMailer dashboard

---

dashboards/nodejs/gc.json

Linked to https://github.com/appsignal/appsignal-nodejs/pull/345, this PR adds a magic dashboard for Node.js heap stats.

Add heap statistics magic dashboard

---

dashboards/sidekiq/main.json

On the Sidekiq magic dashboard, clarify memory usage with "Redis memory
usage", so people don't confuse it with the Sidekiq process memory
usage.
The data is fetched from `Sidekiq.redis_info` which does the same as
`redis-cli info` which is all about Redis data and metrics.
https://github.com/mperham/sidekiq/blob/ed8483784348976edc3943ec235bde14e4626210/lib/sidekiq.rb#L113-L121

Clarify Redis memory usage label

---

dashboards/heroku/status.json

Add Heroku status code dashboard, shows a graph with absolute counts and a relative area graph.

Add Heroku status dashboard

---

dashboards/puma/main.json

Update the description of the `puma_pool_capacity` metric, which is the
`pool_capacity` in Puma. I've updated it to match the Puma docs more
closely:
> pool_capacity: the number of requests that the server is capable of
> taking right now. For example if the number is 5 then it means there
> are 5 threads sitting idle ready to take a request. If one request
> comes in, then the value would be 4 until it finishes processing. If
> the minimum threads allowed is zero, this number will still have a
> maximum value of the maximum threads allowed.
https://github.com/puma/puma/blob/0256d71e607eb8b5fb39e77541dc3ca4db136e86/docs/stats.md

Update Puma pool capacity description

---

dashboards/erlang/main.json

This PR depends on
https://github.com/appsignal/appsignal-elixir/pull/651 which tracks
metrics for the Erlang atom usage.

Add graph for Erlang atom usage

---

dashboards/erlang/main.json

This commit adds a graph displaying the scheduler utilization metric. It shows a line for each of the schedulers in the Erlang node that is being monitored, mimicking the UI of the Erlang observer.

Add scheduler utilization to Erlang magic dashboard

---

dashboards/erlang/main.json

The run queue length for a given scheduler is an interesting metric to be able to observe, especially alongside the scheduler utilization metric. The metric is already being reported by the Erlang probe in the Elixir integration, but it is not displayed in the magic dashboard. This commit adds a graph of run queue lengths to the magic dashboard.

Add run queue length to Erlang magic dashboard

---

dashboards/nodejs/gc.json

This commit adds the `hostname` tag to the magic dashboard configuration for the Node.js V8 heap statistics probe, to match the implementation changes in [appsignal-nodejs#543][pr]. It also removes the `nodejs_peak_malloced_memory` metric, which was never sent by the Node.js V8 heap statistics probe.
[pr]: https://github.com/appsignal/appsignal-nodejs/pull/543
This PR completes the second task in [appsignal-nodejs#543][issue].
[issue]: https://github.com/appsignal/appsignal-nodejs/issues/540

Add hostname to V8 dashboard

---

dashboards/ruby_vm/main.json

We've noticed that distributions are not a good fit for this. For more
PR https://github.com/appsignal/appsignal-ruby/pull/866 on the Ruby gem.
The added hostname tag allows us to tell multiple hosts from each other
and graph them separately. If we do not, an app with multiple hosts
would have hosts overwrite one another's metrics. Only the last reported
value would be stored and shown.
I think we're recording time here, so let's display it as time too.
It's not reporting any values unless the GC profiler is enabled, which
it isn't by default. I want to avoid confusion by shipping an always
empty graph by default so I'm removing it now.
We can always add it back later.

Display Ruby VM probe metrics as gauges with a hostname tag

---

dashboards/ruby_vm/main.json

Add the Garbage Collection time graph back to the Ruby VM dashboard
after it was added and removed in PR
https://github.com/appsignal/public_config/pull/38.
I've updated the metric name to `gc_time` in Ruby gem PR because it
doesn't report the total time anymore:
https://github.com/appsignal/appsignal-ruby/pull/874
https://github.com/appsignal/appsignal-ruby/pull/867
This graph will not have any data by default. We need a way to direct
users to our docs on how to enable this. We cannot link to this from the
graph description that I could tell, the graph description does not
support any link format.
We need to write some docs for this, basically saying: Add
`GC::Profiler.enable` to your app, but not in production or not for long
in production because it may negatively impact the …

Add Garbage Collection time graph to Ruby VM

---

.semaphore/semaphore.yml
README.md
Rakefile
dashboards/active_job/main.json
dashboards/erlang/main.json
dashboards/heroku/status.json
dashboards/mongodb/main.json
dashboards/nextjs/main.json
dashboards/process_memory/main.json
dashboards/puma/main.json
dashboards/sidekiq/main.json
dashboards/web-vitals/main.json

Check if required fields are present. Check this on the dashboard,
visual, metric, metric fields and metric tags levels.
I tried to keep these validations very basic. I don't want over engineer
this for this first version. We can always expand it later.
Things to add, if we want:
- Basic type checking
- Enum value checking (display, format and format_input fields)
- Invalid fields: is a field specified that does nothing
- etc.
Fields with default values that are currently not present in all
dashboards, are now required. I'll fix any validation issues in the next
commit.
These fields are `draw_null_as_zero` and `format`. The
`draw_null_as_zero` field has `true` as default value in the database
and the `format` field is always set by the creation code.
These fields are always set upon …

Add validation to CI

---

dashboards/oban/main.json

This is basically the same magic dashboard that was provided as a gist along with the [Oban test setup](https://github.com/appsignal/test-setups/pull/78).
Part of appsignal/appsignal-elixir#805.

Add Oban magic dashboard

---

dashboards/nginx/main.json

Adds a dashboard with key graphs for the NGINX metrics.
Part of https://github.com/appsignal/appsignal-agent/issues/872.

Add NGINX dashboard

---

dashboards/ruby_vm/gvl.json

The dashboard can be triggered on either of the metrics, as they can be individually enabled and disabled.
Closes https://github.com/appsignal/appsignal-ruby/issues/932.

Add global VM lock dashboard

---

README.md
dashboards/nextjs/README.md
dashboards/nodejs/README.md
dashboards/web-vitals/README.md

Adds a README for each deprecated dashboard (Node.js Postgres, Next.js and Web Vitals) explaining that the dashboard is deprecated (and not explaining the actual dashboard)
A re-do of #49. Part of #46.

Add READMEs for deprecated dashboards

---

dashboards/postgres/README.md
dashboards/postgres/main.json

From Vector's
docs (https://vector.dev/docs/reference/configuration/sources/postgresql_metrics/#pg_stat_database_xact_rollback_total), here's the list of all metrics we receive from the Vector sink in a list:
This patch adds a magic dashboard that includes the checked items in the list above, in alphabetical order as listed in Vector's documentation.
Update of #54
Closes #54
[skip review]

Add Vector PostgreSQL Auto Dashboard

---

dashboards/postgres/main.json

- Reorder the graphs to put the more important graphs at the top.
- Add a dashboard description.
- Improve the graph titles with a human readable label, rather than the
metric name.
- Make sure all graphs have a description.
Improve the formatting of the line label by changing the order a bit.
- Remove the metric name itself. It's long and doesn't add much.
- Put the host first with the database second. Easier to find which host
and database the metric is about.
- Remove the endpoint. It's long and doesn't add all that much. It
contains additional information that could be useful in more detail
oriented views, but currently contains information like the host,
database and port that's either already shown or not relevant.
Part of https://github.com/appsignal/integration-guide/issues/164

Improve PostgreSQL dashboard labels and descriptions

---

dashboards/erlang/main.json

As discussed on https://github.com/appsignal/public_config/pull/56#discussion_r1364995004, this graph uses the value as kilobyte, but currently shows it as a number without context what that number means.
Update the graph definition to show the value as a file size.
[skip review]

Update Erlang IO graph value format

---

dashboards/mongodb_vector/README.md
dashboards/mongodb_vector/main.json
dashboards/mongodb_vector/replication.json
dashboards/mongodb_vector/wiredtiger.json
dashboards/postgres/README.md
dashboards/postgres/main.json

Part of https://github.com/appsignal/appsignal-processor-rs/issues/1337.
The metrics contain the `"vector_namespace"` tags implemented in the [Vector namespace tag processor PR](https://github.com/appsignal/appsignal-processor-rs/pull/1348).
See https://github.com/appsignal/test-setups/pull/161 for a test setup that will send these metrics.

Add MongoDB + Vector dashboards

---

dashboards/heroku/postgres.json

* Add WAL (Write Ahead Log) metrics for the Heroku Postgres add-on ( https://devcenter.heroku.com/articles/postgres-write-ahead-log-usage ) 
* Add Follower lag metrics for the Heroku Postgres add-on
Related processor change: https://github.com/appsignal/appsignal-processor-rs/pull/1426

Add WAL metrics, and Follower lag for followers

---

dashboards/kubernetes/README.md
dashboards/kubernetes/node.json

AppSignal for Kubernetes extracts node metrics for each node running in a Kubenetes cluster. This automated dashboard displays some of those metrics in an automated dashboard named "Kubernetes Nodes".

Add add Automated Dashboard for Kubernetes Node metrics

---

dashboards/kubernetes/README.md
dashboards/kubernetes/node.json

AppSignal for Kubernetes extracts node metrics for each node running in a Kubenetes cluster. This automated dashboard displays some of those metrics in an automated dashboard named "Kubernetes Nodes".
Continuation of #64.

Add add autmated dashboard for Kubernetes Node metrics

---

dashboards/kubernetes/README.md
dashboards/kubernetes/pod.json

Much like #64, but for pods. Part of https://github.com/appsignal/appsignal-kubernetes/pull/2.

Add dashboard for Kubernetes pods

---

dashboards/ruby_vm/gvl.json

Use the GVL per-process tags implemented in https://github.com/appsignal/appsignal-ruby/pull/1129 in the magic dashboard.

Use GVL per-process tags

---

dashboards/active_job/README.md
dashboards/active_job/main.json

This graph displays the queue time per queue.
See PR for more details:
https://github.com/appsignal/appsignal-ruby/pull/1412

Add active_job_queue_time to Active Job Dashboard
